dbt-athena:
-   'dbt-athena/src/**'
-   'dbt-athena/hatch.toml'
-   'dbt-athena/pyproject.toml'
-   'dbt-adapters/src/**'
-   'dbt-adapters/pyproject.toml'
-   'dbt-athena/tests/functional/**'
-   'dbt-athena/tests/__init__.py'
dbt-bigquery:
-   'dbt-bigquery/src/**'
-   'dbt-bigquery/hatch.toml'
-   'dbt-bigquery/pyproject.toml'
-   'dbt-adapters/src/**'
-   'dbt-adapters/pyproject.toml'
-   'dbt-bigquery/tests/functional/**'
-   'dbt-bigquery/tests/__init__.py'
-   'dbt-bigquery/tests/conftest.py'
dbt-postgres:
-   'disabled/dbt-postgres/src/**'
-   'disabled/dbt-postgres/hatch.toml'
-   'disabled/dbt-postgres/pyproject.toml'
-   'disabled/dbt-adapters/src/**'
-   'disabled/dbt-adapters/pyproject.toml'
-   'disabled/dbt-postgres/tests/functional/**'
-   'disabled/dbt-postgres/tests/conftest.py'
dbt-redshift:
-   'dbt-redshift/src/**'
-   'dbt-redshift/hatch.toml'
-   'dbt-redshift/pyproject.toml'
-   'dbt-adapters/src/**'
-   'dbt-adapters/pyproject.toml'
-   'dbt-postgres/src/dbt/include/**'
-   'dbt-redshift/tests/functional/**'
-   'dbt-redshift/tests/__init__.py'
-   'dbt-redshift/tests/conftest.py'
dbt-snowflake:
-   'dbt-snowflake/src/**'
-   'dbt-snowflake/hatch.toml'
-   'dbt-snowflake/pyproject.toml'
-   'dbt-adapters/src/**'
-   'dbt-adapters/pyproject.toml'
-   'dbt-snowflake/tests/functional/**'
-   'dbt-snowflake/tests/__init__.py'
-   'dbt-snowflake/tests/conftest.py'
dbt-spark:
-   'dbt-spark/src/**'
-   'dbt-spark/hatch.toml'
-   'dbt-spark/pyproject.toml'
-   'dbt-adapters/src/**'
-   'dbt-adapters/pyproject.toml'
-   'dbt-spark/tests/functional/**'
-   'dbt-spark/tests/__init__.py'
-   'dbt-spark/tests/conftest.py'
-   'dbt-spark/dagger/**'
